color_range_list:
  black:
    max:
    - 45
    - 150
    - 150
    min:
    - 0
    - 100
    - 100
  blue:
    max:
    - 255
    - 172
    - 97
    min:
    - 44
    - 120
    - 56
  green:
    max:
    - 172
    - 115
    - 205
    min:
    - 20
    - 54
    - 127
  red:
    max:
    - 242
    - 174
    - 205
    min:
    - 48
    - 151
    - 135
  white:
    max:
    - 255
    - 155
    - 155
    min:
    - 110
    - 100
    - 100
  yellow:
    max:
    - 255
    - 177
    - 184
    min:
    - 195
    - 110
    - 146
