color_range_list:
  black:
    max:
    - 45
    - 150
    - 150
    min:
    - 0
    - 100
    - 100
  blue:
    max:
    - 255
    - 179
    - 91
    min:
    - 164
    - 99
    - 68
  green:
    max:
    - 172
    - 110
    - 202
    min:
    - 20
    - 84
    - 131
  red:
    max:
    - 243
    - 170
    - 183
    min:
    - 37
    - 131
    - 134
  white:
    max:
    - 255
    - 155
    - 155
    min:
    - 110
    - 100
    - 100
  yellow:
    max:
    - 255
    - 177
    - 184
    min:
    - 195
    - 110
    - 146
